# DON'T DELETE THIS, THIS IS MEANT FOR OUR JPA REPO TESTS
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  datasource:
    url: jdbc:tc:postgresql:17.9-alpine:///testdb
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none   # Use Flyway for schema creation, not Hibernate
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
        jdbc:
          "[time_zone]": UTC
  flyway:
    enabled: true
    schemas:
      - public
    locations: classpath:db/migration
    baseline-on-migrate: true # This prevents Flyway from failing if @BeforeAll already did something
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    health:
      show-details: always

postgres:
  version: ${POSTGRES_VERSION}

logging:
  level:
    "[org.hibernate.SQL]": debug
    