/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/portfolios/{portfolioId}/accounts/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get account summary
         * @description Returns a single account with current positions and live market valuation.
         */
        get: operations["getAccount"];
        /**
         * Update account details
         * @description Updates mutable properties of an account like its display name.
         */
        put: operations["updateAccount"];
        post?: never;
        /**
         * Close an account
         * @description Transitions account to CLOSED state. Requires zero balance and no open positions.
         */
        delete: operations["closeAccount"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all portfolios
         * @description Returns a summary list of all portfolios owned by the authenticated user.
         */
        get: operations["getPortfolios"];
        put?: never;
        /**
         * Create a new portfolio
         * @description Initializes a portfolio for the authenticated user. Can optionally create a default account automatically.
         */
        post: operations["createPortfolio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolioId}/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all accounts
         * @description Returns all accounts in the portfolio. Note: Fetches fresh market data; cache results where possible.
         */
        get: operations["getAllAccounts"];
        put?: never;
        /**
         * Create a new account
         * @description Initializes a new account within a portfolio with a specific currency and strategy.
         */
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolioId}/accounts/{accountId}/transactions/withdrawal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record a Withdrawal
         * @description Decreases account cash balance.
         */
        post: operations["recordWithdrawal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolioId}/accounts/{accountId}/transactions/transfer-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Transfer Out
         * @description Records cash moving out of the account.
         */
        post: operations["recordTransferOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolioId}/accounts/{accountId}/transactions/transfer-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Transfer In
         * @description Records cash moving into the account.
         */
        post: operations["recordTransferIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolioId}/accounts/{accountId}/transactions/split": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record a SPLIT
         * @description Adjusts asset quantity and basis via a ratio. No cash impact.
         */
        post: operations["recordSplit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolioId}/accounts/{accountId}/transactions/sell": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record a SELL
         * @description Increases cash and decreases asset quantity. Triggers realized gain/loss calculation.
         */
        post: operations["recordSell"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolioId}/accounts/{accountId}/transactions/return-of-capital": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Return of Capital
         * @description Reduces asset cost basis. Triggers cash increase.
         */
        post: operations["recordReturnOfCapital"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolioId}/accounts/{accountId}/transactions/interest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Interest
         * @description Records interest earned on cash or a specific asset.
         */
        post: operations["recordInterest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolioId}/accounts/{accountId}/transactions/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload transaction CSV
         * @description Processes a multipart CSV file. Validates all rows before committing. Returns row-level errors on failure.
         */
        post: operations["importCsv"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolioId}/accounts/{accountId}/transactions/fee": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record a Fee
         * @description Records an expense/fee against the cash balance.
         */
        post: operations["recordFee"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolioId}/accounts/{accountId}/transactions/drip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record a DRIP
         * @description Dividend reinvestment; creates an income and buy event.
         */
        post: operations["recordDividendReinvestment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolioId}/accounts/{accountId}/transactions/dividend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record a Dividend
         * @description Records cash income from an asset dividend.
         */
        post: operations["recordDividend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolioId}/accounts/{accountId}/transactions/deposit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record a Deposit
         * @description Increases account cash balance.
         */
        post: operations["recordDeposit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolioId}/accounts/{accountId}/transactions/buy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record a BUY
         * @description Decreases cash and increases asset quantity.
         */
        post: operations["recordBuy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market/quotes/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get batch quotes
         * @description Primary endpoint for portfolio views. 20 symbol limit. Uses Redis MGET; fans out to FMP on cache miss. Rate limit: 10/min.
         */
        post: operations["getBatchQuotes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolioId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get portfolio details
         * @description Returns full details for a specific portfolio, including configuration and status.
         */
        get: operations["getPortfolio"];
        put?: never;
        post?: never;
        /**
         * Delete a portfolio
         * @description Removes a portfolio. Standard users are forced to soft-delete. Admins may toggle hard-delete. 'Recursive' will affect all child accounts.
         */
        delete: operations["deletePortfolio"];
        options?: never;
        head?: never;
        /**
         * Update portfolio details
         * @description Updates the name, description, or base currency of an existing portfolio.
         */
        patch: operations["updatePortfolio"];
        trace?: never;
    };
    "/api/v1/portfolios/{portfolioId}/accounts/{accountId}/transactions/{transactionId}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Restore transaction
         * @description Re-activates a previously excluded transaction.
         */
        patch: operations["restoreTransaction"];
        trace?: never;
    };
    "/api/v1/portfolios/{portfolioId}/accounts/{accountId}/transactions/{transactionId}/exclude": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Exclude transaction
         * @description Soft-removes a transaction from P&L and position calculations.
         */
        patch: operations["excludeTransaction"];
        trace?: never;
    };
    "/api/v1/portfolios/{portfolioId}/accounts/{accountId}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Reopen a closed account
         * @description Transitions a CLOSED account back to ACTIVE, preserving all history.
         */
        patch: operations["reopenAccount"];
        trace?: never;
    };
    "/api/v1/portfolios/{portfolioId}/net-worth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get portfolio net worth
         * @description Calculates the total valuation of the portfolio in its base currency. Triggers real-time valuation of all underlying assets.
         */
        get: operations["getNetWorth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolioId}/accounts/{accountId}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get transaction history
         * @description Paginated list of transactions with optional filtering.
         */
        get: operations["getTransactionHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolioId}/accounts/{accountId}/transactions/{transactionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get single transaction
         * @description Retrieves a transaction by its unique ID.
         */
        get: operations["getTransaction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolioId}/accounts/{accountId}/transactions/import/template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download CSV template
         * @description Returns a blank CSV template with the required headers for bulk transaction importing.
         */
        get: operations["getTemplate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolioId}/accounts/{accountId}/realized-gains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get realized gains ledger
         * @description Returns a breakdown of capital gains and losses, including pre-computed totals. Results are sorted by occurrence date (descending). Database-backed and safe for high-frequency polling.
         */
        get: operations["getRealizedGains"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/net-worth/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get historical net worth
         * @description Returns a time-series list of net worth snapshots for the authenticated user. Maximum range is 5 years (1825 days).
         */
        get: operations["getHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market/validate/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Validate and seed a symbol
         * @description Must be called before a BUY transaction. Checks DB cache, then FMP API. Seeds the internal database if found. Rate limit: 20/min.
         */
        get: operations["validateSymbol"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Autocomplete symbol search
         * @description Searches for tradeable symbols. Returns shallow results (name, exchange). Client should debounce at least 300ms. Rate limit: 30/min.
         */
        get: operations["searchSymbols"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market/quotes/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get single quote
         * @description Redis-cached (5m TTL). Returns 404 if symbol has no historical transaction.
         */
        get: operations["getQuote"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market/info/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get asset metadata
         * @description Returns slow-changing data (sector, type, currency). DB-cached for 7 days.
         */
        get: operations["getAssetInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exchange-rates/supported": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List supported currencies
         * @description Returns all ISO-4217 codes available for exchange rate lookup via the Bank of Canada.
         */
        get: operations["getSupportedCurrencies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exchange-rates/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current exchange rate
         * @description Returns the rate for '1 {from} = X {to}'. Rates are sourced from Bank of Canada and cached for 1 hour. Cross-pairs (e.g. EUR/USD) are computed via CAD triangulation.
         */
        get: operations["getCurrentRate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserId: {
            /** Format: uuid */
            id?: string;
        };
        UpdateAccountRequest: {
            /**
             * @description The new display name for the account
             * @example Main Savings
             */
            accountName: string;
        };
        /** @description Request body for initializing a new investment portfolio */
        CreatePortfolioRequest: {
            /**
             * @description Display name for the portfolio
             * @example Long-Term Retirement
             */
            name: string;
            /**
             * @description Optional notes or goals for this portfolio
             * @example Tax-advantaged accounts only
             */
            description?: string;
            /**
             * @description Base currency for net worth calculation (ISO-4217)
             * @example USD
             */
            currency: string;
            /**
             * @description If true, initializes one default account immediately
             * @example true
             */
            createDefaultAccount: boolean;
            /**
             * @description Type of the default account to be created
             * @enum {string}
             */
            defaultAccountType?: "FHSA" | "TFSA" | "RRSP" | "RESP" | "ROTH_IRA" | "SOLO_401K" | "CHEQUING" | "SAVINGS" | "MARGIN" | "TAXABLE_INVESTMENT" | "NON_REGISTERED_INVESTMENT";
            /**
             * @description Strategy for position tracking in the default account
             * @enum {string}
             */
            defaultStrategy?: "ACB" | "FIFO" | "LIFO" | "SPECIFIC_ID";
        };
        /** @description Financial summary of a specific account within a portfolio */
        AccountSummary: {
            id?: string;
            name?: string;
            type?: string;
            status?: string;
            currency?: string;
            /** Format: double */
            cashBalance?: number;
            /** Format: double */
            totalValue?: number;
            /** Format: int32 */
            assetCount?: number;
            /** Format: date-time */
            creationDate?: string;
            hasCashImbalance?: boolean;
            /** Format: int32 */
            excludedTransactionCount?: number;
        };
        /** @description Full portfolio details including all member accounts */
        PortfolioResponse: {
            id?: string;
            name?: string;
            currency?: string;
            /** Format: double */
            totalValue?: number;
            hasStaleData?: boolean;
            accounts?: components["schemas"]["AccountSummary"][];
            /** Format: date-time */
            creationDate?: string;
            /** Format: date-time */
            lastUpdated?: string;
        };
        CreateAccountRequest: {
            /**
             * @description The display name for the account
             * @example Tech Growth 2026
             */
            accountName: string;
            /**
             * @description The type of account
             * @example TFSA
             * @enum {string}
             */
            accountType: "FHSA" | "TFSA" | "RRSP" | "RESP" | "ROTH_IRA" | "SOLO_401K" | "CHEQUING" | "SAVINGS" | "MARGIN" | "TAXABLE_INVESTMENT" | "NON_REGISTERED_INVESTMENT";
            /**
             * @description The strategy used for cost-basis and tax lot selection
             * @example FIFO
             * @enum {string}
             */
            strategy: "ACB" | "FIFO" | "LIFO" | "SPECIFIC_ID";
            /**
             * @description 3-letter ISO currency code
             * @example USD
             */
            currency: string;
        };
        AccountId: {
            /** Format: uuid */
            id?: string;
        };
        AccountView: {
            accountId?: components["schemas"]["AccountId"];
            name?: string;
            /** @enum {string} */
            type?: "FHSA" | "TFSA" | "RRSP" | "RESP" | "ROTH_IRA" | "SOLO_401K" | "CHEQUING" | "SAVINGS" | "MARGIN" | "TAXABLE_INVESTMENT" | "NON_REGISTERED_INVESTMENT";
            /** @enum {string} */
            status?: "ACTIVE" | "REPLAYING" | "CLOSED";
            assets?: components["schemas"]["PositionView"][];
            baseCurrency?: components["schemas"]["Currency"];
            cashBalance?: components["schemas"]["Money"];
            totalValue?: components["schemas"]["Money"];
            /** Format: date-time */
            creationDate?: string;
            hasCashImbalance?: boolean;
            /** Format: int32 */
            excludedTransactionCount?: number;
        };
        Currency: {
            symbol?: string;
            /** Format: int32 */
            defaultFractionDigits?: number;
            code?: string;
        };
        Money: {
            amount?: number;
            currency?: components["schemas"]["Currency"];
            zero?: boolean;
            negative?: boolean;
            positive?: boolean;
        };
        PercentageChange: {
            change?: number;
            gain?: boolean;
            loss?: boolean;
        };
        PositionView: {
            symbol?: string;
            /** @enum {string} */
            assetType?: "BOND" | "CRYPTO" | "ETF" | "STOCK" | "CASH" | "COMMODITY" | "FOREX_PAIR" | "REAL_ESTATE" | "OTHER";
            quantity?: components["schemas"]["Quantity"];
            totalCostBasis?: components["schemas"]["Price"];
            averageCostPerUnit?: components["schemas"]["Price"];
            totalFeesIncurred?: components["schemas"]["Money"];
            currentPrice?: components["schemas"]["Price"];
            marketValue?: components["schemas"]["Money"];
            unrealizedPnL?: components["schemas"]["Money"];
            returnPercentage?: components["schemas"]["PercentageChange"];
            costBasisMethod?: string;
            /** Format: date-time */
            firstAcquiredDate?: string;
            /** Format: date-time */
            lastModified?: string;
        };
        Price: {
            pricePerUnit?: components["schemas"]["Money"];
            zero?: boolean;
        };
        Quantity: {
            amount?: number;
            zero?: boolean;
            positive?: boolean;
            nonZero?: boolean;
        };
        /** @description Request to record a manual cash withdrawal */
        RecordWithdrawalRequest: {
            /** @example 100 */
            amount: number;
            /** @example USD */
            currency: string;
            /** Format: date-time */
            transactionDate?: string;
            notes?: string;
        };
        ExchangeRate: {
            from?: components["schemas"]["Currency"];
            to?: components["schemas"]["Currency"];
            rate?: number;
            /** Format: date-time */
            quotedAt?: string;
        };
        Fee: {
            /** @enum {string} */
            feeType?: "BROKERAGE" | "COMMISSION" | "SPREAD" | "EXCHANGE_FEE" | "CLEARING_FEE" | "PERFORMANCE_FEE" | "MANAGEMENT_FEE" | "CUSTODY_FEE" | "ACCOUNT_MAINTENANCE" | "WITHDRAWAL_FEE" | "WIRE_TRANSFER_FEE" | "NSF_FEE" | "MARGIN_INTEREST" | "ORIGINATION_FEE" | "PREPAYMENT_PENALTY" | "STAMP_DUTY" | "TRANSACTION_TAX" | "WITHHOLDING_TAX" | "FOREIGN_EXCHANGE_CONVERSION" | "CONVERSION_SPREAD" | "GAS" | "ADVISORY_FEE" | "PLATFORM_FEE" | "OTHER" | "NONE";
            nativeAmount?: components["schemas"]["Money"];
            accountAmount?: components["schemas"]["Money"];
            exchangeRate?: components["schemas"]["ExchangeRate"];
            /** Format: date-time */
            occurredAt?: string;
            metadata?: components["schemas"]["FeeMetadata"];
        };
        FeeMetadata: {
            values?: {
                [key: string]: string;
            };
            empty?: boolean;
        };
        TransactionId: {
            /** Format: uuid */
            id?: string;
        };
        TransactionView: {
            transactionId?: components["schemas"]["TransactionId"];
            /** @enum {string} */
            type?: "BUY" | "SELL" | "DEPOSIT" | "WITHDRAWAL" | "INTEREST" | "FEE" | "DIVIDEND" | "DIVIDEND_REINVEST" | "SPLIT" | "RETURN_OF_CAPITAL" | "TRANSFER_IN" | "TRANSFER_OUT" | "OTHER";
            symbol?: string;
            quantity?: components["schemas"]["Quantity"];
            price?: components["schemas"]["Price"];
            fees?: components["schemas"]["Fee"][];
            totalCost?: components["schemas"]["Money"];
            metadata?: {
                [key: string]: string;
            };
            /** Format: date-time */
            date?: string;
            notes?: string;
        };
        /** @description Request to record a cash transfer out of the account */
        RecordTransferOutRequest: {
            /** @example 250 */
            amount: number;
            /** @example USD */
            currency: string;
            /** Format: date-time */
            transactionDate: string;
            notes?: string;
        };
        /** @description Request to record a cash transfer into the account */
        RecordTransferInRequest: {
            /** @example 5000 */
            amount: number;
            /** @example USD */
            currency: string;
            /** Format: date-time */
            transactionDate: string;
            notes?: string;
        };
        /** @description Request to record a stock split or reverse split */
        RecordSplitRequest: {
            /** @example GOOGL */
            symbol: string;
            /**
             * Format: int32
             * @description New shares count
             * @example 20
             */
            numerator?: number;
            /**
             * Format: int32
             * @description Old shares count
             * @example 1
             */
            denominator?: number;
            /** Format: date-time */
            transactionDate: string;
            notes?: string;
        };
        /** @description Detailed breakdown of a single fee associated with a transaction */
        FeeRequest: {
            /**
             * @description Category of the fee
             * @enum {string}
             */
            feeType: "BROKERAGE" | "COMMISSION" | "SPREAD" | "EXCHANGE_FEE" | "CLEARING_FEE" | "PERFORMANCE_FEE" | "MANAGEMENT_FEE" | "CUSTODY_FEE" | "ACCOUNT_MAINTENANCE" | "WITHDRAWAL_FEE" | "WIRE_TRANSFER_FEE" | "NSF_FEE" | "MARGIN_INTEREST" | "ORIGINATION_FEE" | "PREPAYMENT_PENALTY" | "STAMP_DUTY" | "TRANSACTION_TAX" | "WITHHOLDING_TAX" | "FOREIGN_EXCHANGE_CONVERSION" | "CONVERSION_SPREAD" | "GAS" | "ADVISORY_FEE" | "PLATFORM_FEE" | "OTHER" | "NONE";
            /**
             * @description Cost of the fee
             * @example 9.99
             */
            amount: number;
            /**
             * @description Currency the fee was charged in
             * @example USD
             */
            currency: string;
        };
        /** @description Request to record an asset sale (Sell) */
        RecordSaleRequest: {
            /** @example NVDA */
            symbol: string;
            /** @example 5 */
            quantity: number;
            /** @example 900 */
            price: number;
            /** @example USD */
            currency: string;
            fees?: components["schemas"]["FeeRequest"][];
            /** Format: date-time */
            transactionDate?: string;
            notes?: string;
        };
        /** @description Request to record Return of Capital (ROC) */
        RecordReturnOfCapitalRequest: {
            /** @example XRE.TO */
            assetSymbol: string;
            /**
             * @description Amount per unit returned
             * @example 0.0512
             */
            distributionPerUnit: number;
            /** @example CAD */
            currency: string;
            /**
             * @description Total units held at time of distribution
             * @example 100
             */
            heldQuantity: number;
            /** Format: date-time */
            transactionDate: string;
            notes?: string;
        };
        /** @description Request to record interest income (Cash or Asset-based) */
        RecordInterestRequest: {
            /**
             * @description Optional ticker if interest is from a specific bond/GIC
             * @example O
             */
            assetSymbol?: string;
            /** @example 15.25 */
            amount: number;
            /** @example CAD */
            currency: string;
            /** Format: date-time */
            transactionDate: string;
            notes?: string;
            assetInterest?: boolean;
        };
        /** @description Response object for bulk CSV transaction imports */
        CsvImportResult: {
            /**
             * @description Indicates if the entire batch was processed successfully
             * @example true
             */
            success?: boolean;
            /**
             * Format: int32
             * @description The total number of transactions successfully saved to the database
             * @example 42
             */
            rowsCommitted?: number;
            /** @description A list of validation or processing errors, populated only if success is false */
            errors?: components["schemas"]["CsvRowError"][];
        };
        /** @description A list of validation or processing errors, populated only if success is false */
        CsvRowError: {
            /** Format: int32 */
            rowNum?: number;
            message?: string;
        };
        /** @description Request to record a standalone fee (e.g. Account Maintenance) */
        RecordStandaloneFeeRequest: {
            /** @example 50 */
            amount: number;
            /** @example USD */
            currency: string;
            /** @enum {string} */
            feeType: "BROKERAGE" | "COMMISSION" | "SPREAD" | "EXCHANGE_FEE" | "CLEARING_FEE" | "PERFORMANCE_FEE" | "MANAGEMENT_FEE" | "CUSTODY_FEE" | "ACCOUNT_MAINTENANCE" | "WITHDRAWAL_FEE" | "WIRE_TRANSFER_FEE" | "NSF_FEE" | "MARGIN_INTEREST" | "ORIGINATION_FEE" | "PREPAYMENT_PENALTY" | "STAMP_DUTY" | "TRANSACTION_TAX" | "WITHHOLDING_TAX" | "FOREIGN_EXCHANGE_CONVERSION" | "CONVERSION_SPREAD" | "GAS" | "ADVISORY_FEE" | "PLATFORM_FEE" | "OTHER" | "NONE";
            /** Format: date-time */
            transactionDate?: string;
            notes?: string;
        };
        /** @description Request to record a Dividend Reinvestment (DRIP) */
        RecordDRIPRequest: {
            /** @example MSFT */
            assetSymbol: string;
            /**
             * @description Number of new shares acquired
             * @example 0.4521
             */
            sharesPurchased: number;
            /**
             * @description Price per share at time of reinvestment
             * @example 420.1
             */
            pricePerShare: number;
            /** @example USD */
            currency: string;
            /** Format: date-time */
            transactionDate: string;
            notes?: string;
        };
        /** @description Request to record a cash dividend payment */
        RecordDividendRequest: {
            /** @example AAPL */
            assetSymbol: string;
            /**
             * @description Total dividend amount received
             * @example 25.5
             */
            amount: number;
            /** @example USD */
            currency: string;
            /** Format: date-time */
            transactionDate: string;
            notes?: string;
        };
        /** @description Request to record a manual cash deposit */
        RecordDepositRequest: {
            /** @example 1000 */
            amount: number;
            /** @example USD */
            currency: string;
            /**
             * Format: date-time
             * @description UTC timestamp of the deposit
             */
            transactionDate?: string;
            /** @example Monthly savings contribution */
            notes?: string;
        };
        /** @description Request to record an asset purchase (Buy) */
        RecordPurchaseRequest: {
            /** @example TSLA */
            symbol: string;
            /** @enum {string} */
            type: "BOND" | "CRYPTO" | "ETF" | "STOCK" | "CASH" | "COMMODITY" | "FOREX_PAIR" | "REAL_ESTATE" | "OTHER";
            /**
             * @description Quantity bought (supports fractional)
             * @example 10
             */
            quantity: number;
            /**
             * @description Price per unit
             * @example 175.5
             */
            price: number;
            /** @example USD */
            currency: string;
            /** @description Associated transaction fees (e.g., commissions) */
            fees?: components["schemas"]["FeeRequest"][];
            /** Format: date-time */
            transactionDate?: string;
            notes?: string;
        };
        /** @description Request body for retrieving multiple asset quotes in one call */
        BatchQuoteRequest: {
            /**
             * @description List of ticker symbols (e.g., AAPL, BTC-USD)
             * @example [
             *       "AAPL",
             *       "MSFT"
             *     ]
             */
            symbols: string[];
        };
        /** @description Real-time or cached market price data */
        MarketQuoteResponse: {
            symbol?: string;
            /** Format: double */
            currentPrice?: number;
            /** Format: double */
            openPrice?: number;
            /** Format: double */
            highPrice?: number;
            /** Format: double */
            lowPrice?: number;
            /** Format: double */
            previousClose?: number;
            /** Format: double */
            changePercent?: number;
            /** Format: double */
            changeAmount?: number;
            currency?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        /** @description Request body for modifying an existing portfolio's metadata */
        UpdatePortfolioRequest: {
            /**
             * @description Updated name
             * @example Global Wealth
             */
            name?: string;
            /**
             * @description Updated description
             * @example Updated goals for 2026
             */
            description?: string;
            /**
             * @description Updated base currency code
             * @example CAD
             */
            currency?: string;
        };
        /** @description Request to exclude a transaction from performance calculations */
        ExcludeTransactionRequest: {
            /**
             * @description Reason for exclusion (e.g., duplicate, internal transfer error)
             * @example Duplicate entry
             */
            reason: string;
        };
        /** @description High-level portfolio data for list/dashboard views */
        PortfolioSummaryResponse: {
            id?: string;
            name?: string;
            currency?: string;
            /** Format: double */
            totalValue?: number;
        };
        /** @description Current valuation of the entire portfolio */
        NetWorthResponse: {
            /** Format: double */
            totalNetWorth?: number;
            currency?: string;
        };
        PageAccountView: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["AccountView"][];
            /** Format: int32 */
            number?: number;
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            sort?: components["schemas"]["SortObject"];
            empty?: boolean;
        };
        PageableObject: {
            /** Format: int64 */
            offset?: number;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int32 */
            pageNumber?: number;
            unpaged?: boolean;
            paged?: boolean;
            sort?: components["schemas"]["SortObject"];
        };
        SortObject: {
            empty?: boolean;
            unsorted?: boolean;
            sorted?: boolean;
        };
        PageTransactionView: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["TransactionView"][];
            /** Format: int32 */
            number?: number;
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            sort?: components["schemas"]["SortObject"];
            empty?: boolean;
        };
        /** @description Universal money representation for high-precision values */
        MoneyResponse: {
            /** @example 1250.75 */
            amount?: number;
            /** @example USD */
            currency?: string;
        };
        /** @description Individual line item for a realized capital gain/loss */
        RealizedGainItemResponse: {
            symbol?: string;
            realizedGainLoss?: components["schemas"]["MoneyResponse"];
            costBasisSold?: components["schemas"]["MoneyResponse"];
            /** Format: date-time */
            occurredAt?: string;
            isGain?: boolean;
            isLoss?: boolean;
        };
        /** @description Aggregated capital gains report for a specific tax year */
        RealizedGainsSummaryResponse: {
            items?: components["schemas"]["RealizedGainItemResponse"][];
            totalGains?: components["schemas"]["MoneyResponse"];
            totalLosses?: components["schemas"]["MoneyResponse"];
            netGainLoss?: components["schemas"]["MoneyResponse"];
            currency?: string;
            /** Format: int32 */
            taxYear?: number;
            /** Format: int32 */
            itemCount?: number;
        };
        /** @description A point-in-time snapshot of the user's total net worth */
        NetWorthSnapshotResponse: {
            /**
             * Format: double
             * @description Total net worth (Assets - Liabilities)
             * @example 125000.5
             */
            netWorth?: number;
            /**
             * Format: double
             * @description Sum of all active account balances
             * @example 150000
             */
            totalAssets?: number;
            /**
             * Format: double
             * @description Sum of all debts/margin (expressed as a positive number)
             * @example 25000.5
             */
            totalLiabilities?: number;
            /**
             * @description ISO-4217 currency code used for the calculation
             * @example USD
             */
            currency?: string;
            /** @description True if some prices were missing and cost-basis was used instead */
            hasStaleData?: boolean;
            /**
             * Format: date-time
             * @description UTC timestamp when the snapshot was recorded
             */
            snapshotDate?: string;
        };
        /** @description Detailed asset metadata including sector and exchange information */
        AssetInfoResponse: {
            symbol?: string;
            name?: string;
            assetType?: string;
            exchange?: string;
            tradingCurrency?: string;
            sector?: string;
            description?: string;
        };
        /** @description Result of a ticker/symbol search */
        SymbolSearchResponse: {
            symbol?: string;
            name?: string;
            exchange?: string;
            tradingCurrency?: string;
        };
        /** @description List of all currencies supported for live exchange rates */
        SupportedCurrenciesResponse: {
            currencies?: string[];
        };
        /** @description Currency conversion rate information */
        ExchangeRateResponse: {
            /** @example USD */
            from?: string;
            /** @example CAD */
            to?: string;
            /** @example 1.355 */
            rate?: number;
            /** Format: date-time */
            quotedAt?: string;
            isIdentity?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAccount: {
        parameters: {
            query: {
                userId: components["schemas"]["UserId"];
            };
            header?: never;
            path: {
                portfolioId: string;
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    updateAccount: {
        parameters: {
            query: {
                userId: components["schemas"]["UserId"];
            };
            header?: never;
            path: {
                portfolioId: string;
                accountId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAccountRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    closeAccount: {
        parameters: {
            query: {
                userId: components["schemas"]["UserId"];
            };
            header?: never;
            path: {
                portfolioId: string;
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account closed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
            /** @description Conflict: Account has remaining balance or positions */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPortfolios: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PortfolioSummaryResponse"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    createPortfolio: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePortfolioRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PortfolioResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    getAllAccounts: {
        parameters: {
            query: {
                userId: components["schemas"]["UserId"];
                /** @description Zero-based page index */
                page?: number;
                /** @description Page size */
                size?: number;
            };
            header?: never;
            path: {
                portfolioId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageAccountView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    createAccount: {
        parameters: {
            query: {
                userId: components["schemas"]["UserId"];
            };
            header?: never;
            path: {
                /** @example UUID */
                portfolioId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountRequest"];
            };
        };
        responses: {
            /** @description Account created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    recordWithdrawal: {
        parameters: {
            query: {
                userId: components["schemas"]["UserId"];
            };
            header?: {
                /** @description Optional UUID for safe retries */
                "Idempotency-Key"?: string;
            };
            path: {
                portfolioId: string;
                accountId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordWithdrawalRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TransactionView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    recordTransferOut: {
        parameters: {
            query: {
                userId: components["schemas"]["UserId"];
            };
            header?: {
                /** @description Optional UUID for safe retries */
                "Idempotency-Key"?: string;
            };
            path: {
                portfolioId: string;
                accountId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordTransferOutRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TransactionView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    recordTransferIn: {
        parameters: {
            query: {
                userId: components["schemas"]["UserId"];
            };
            header?: {
                /** @description Optional UUID for safe retries */
                "Idempotency-Key"?: string;
            };
            path: {
                portfolioId: string;
                accountId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordTransferInRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TransactionView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    recordSplit: {
        parameters: {
            query: {
                userId: components["schemas"]["UserId"];
            };
            header?: {
                /** @description Optional UUID for safe retries */
                "Idempotency-Key"?: string;
            };
            path: {
                portfolioId: string;
                accountId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordSplitRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TransactionView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    recordSell: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional UUID for safe retries */
                "Idempotency-Key"?: string;
            };
            path: {
                portfolioId: string;
                accountId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordSaleRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TransactionView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    recordReturnOfCapital: {
        parameters: {
            query: {
                userId: components["schemas"]["UserId"];
            };
            header?: {
                /** @description Optional UUID for safe retries */
                "Idempotency-Key"?: string;
            };
            path: {
                portfolioId: string;
                accountId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordReturnOfCapitalRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TransactionView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    recordInterest: {
        parameters: {
            query: {
                userId: components["schemas"]["UserId"];
            };
            header?: {
                /** @description Optional UUID for safe retries */
                "Idempotency-Key"?: string;
            };
            path: {
                portfolioId: string;
                accountId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordInterestRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TransactionView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    importCsv: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example p-123 */
                portfolioId: string;
                /** @example acc-456 */
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    userId?: components["schemas"]["UserId"];
                    /**
                     * Format: binary
                     * @description The CSV file to upload
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Import successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CsvImportResult"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
            /** @description File size exceeds 5MB limit */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CsvImportResult"];
                };
            };
            /** @description Unsupported file type (must be CSV) */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CsvImportResult"];
                };
            };
            /** @description Validation failed for one or more rows */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CsvImportResult"];
                };
            };
        };
    };
    recordFee: {
        parameters: {
            query: {
                userId: components["schemas"]["UserId"];
            };
            header?: {
                /** @description Optional UUID for safe retries */
                "Idempotency-Key"?: string;
            };
            path: {
                portfolioId: string;
                accountId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordStandaloneFeeRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TransactionView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    recordDividendReinvestment: {
        parameters: {
            query: {
                userId: components["schemas"]["UserId"];
            };
            header?: {
                /** @description Optional UUID for safe retries */
                "Idempotency-Key"?: string;
            };
            path: {
                portfolioId: string;
                accountId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordDRIPRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TransactionView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    recordDividend: {
        parameters: {
            query: {
                userId: components["schemas"]["UserId"];
            };
            header?: {
                /** @description Optional UUID for safe retries */
                "Idempotency-Key"?: string;
            };
            path: {
                portfolioId: string;
                accountId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordDividendRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TransactionView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    recordDeposit: {
        parameters: {
            query: {
                userId: components["schemas"]["UserId"];
            };
            header?: {
                /** @description Optional UUID for safe retries */
                "Idempotency-Key"?: string;
            };
            path: {
                portfolioId: string;
                accountId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordDepositRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TransactionView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    recordBuy: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional UUID for safe retries */
                "Idempotency-Key"?: string;
            };
            path: {
                portfolioId: string;
                accountId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordPurchaseRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TransactionView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    getBatchQuotes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List of symbols (max 20) */
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchQuoteRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: components["schemas"]["MarketQuoteResponse"];
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    getPortfolio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolioId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PortfolioResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    deletePortfolio: {
        parameters: {
            query?: {
                /** @description If true, data is hidden but not wiped. Forced to true for non-admins. */
                softDelete?: boolean;
                /** @description If true, deletes all associated accounts and transactions. */
                recursive?: boolean;
            };
            header?: never;
            path: {
                portfolioId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Portfolio successfully deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
            /** @description Unauthorized access to portfolio */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updatePortfolio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolioId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePortfolioRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PortfolioResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    restoreTransaction: {
        parameters: {
            query: {
                userId: components["schemas"]["UserId"];
            };
            header: {
                /** @description UUID for safe retries */
                "Idempotency-Key": string;
            };
            path: {
                portfolioId: string;
                accountId: string;
                transactionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TransactionView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    excludeTransaction: {
        parameters: {
            query: {
                userId: components["schemas"]["UserId"];
            };
            header: {
                /** @description UUID for safe retries */
                "Idempotency-Key": string;
            };
            path: {
                portfolioId: string;
                accountId: string;
                transactionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExcludeTransactionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TransactionView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    reopenAccount: {
        parameters: {
            query: {
                userId: components["schemas"]["UserId"];
            };
            header?: never;
            path: {
                portfolioId: string;
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    getNetWorth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolioId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NetWorthResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    getTransactionHistory: {
        parameters: {
            query: {
                userId: components["schemas"]["UserId"];
                /** @description Filter by ticker symbol */
                symbol?: string;
                /** @description Filter by start date */
                startDate?: string;
                /** @description Filter by end date */
                endDate?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                portfolioId: string;
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageTransactionView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    getTransaction: {
        parameters: {
            query: {
                userId: components["schemas"]["UserId"];
            };
            header?: never;
            path: {
                portfolioId: string;
                accountId: string;
                transactionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transaction found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TransactionView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
            /** @description Transaction not found or access denied */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TransactionView"];
                };
            };
        };
    };
    getTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV file stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    getRealizedGains: {
        parameters: {
            query?: {
                /** @description Filter by UTC tax year (e.g., 2024). Cannot be in the future. */
                taxYear?: number;
                /** @description Filter by specific ticker (e.g., AAPL). */
                symbol?: string;
                /** @description Page number for pagination */
                page?: number;
                /** @description Items per page */
                size?: number;
            };
            header?: never;
            path: {
                /** @description The unique ID of the portfolio */
                portfolioId: string;
                /** @description The unique ID of the account */
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ledger retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RealizedGainsSummaryResponse"];
                };
            };
            /** @description Invalid tax year or symbol format */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
            /** @description Account not found or access denied */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RealizedGainsSummaryResponse"];
                };
            };
        };
    };
    getHistory: {
        parameters: {
            query: {
                userId: components["schemas"]["UserId"];
                /**
                 * @description Number of days of history to retrieve
                 * @example 90
                 */
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NetWorthSnapshotResponse"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    validateSymbol: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Symbol validated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AssetInfoResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
            /** @description Symbol not found in external provider */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AssetInfoResponse"];
                };
            };
        };
    };
    searchSymbols: {
        parameters: {
            query: {
                /** @description Search query (ticker or company name) */
                query: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SymbolSearchResponse"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    getQuote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Quote retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MarketQuoteResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
            /** @description No quote found or asset unseeded */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MarketQuoteResponse"];
                };
            };
        };
    };
    getAssetInfo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AssetInfoResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    getSupportedCurrencies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SupportedCurrenciesResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    getCurrentRate: {
        parameters: {
            query: {
                /**
                 * @description Base currency code (e.g., USD)
                 * @example USD
                 */
                from: string;
                /**
                 * @description Target currency code (e.g., CAD)
                 * @example CAD
                 */
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful rate lookup */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ExchangeRateResponse"];
                };
            };
            /** @description Invalid ISO-4217 currency code format */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
            /** @description Currency pair not supported by source */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ExchangeRateResponse"];
                };
            };
            /** @description Source API (BOC) unreachable - client should use cost-basis fallback */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ExchangeRateResponse"];
                };
            };
        };
    };
}
