package com.laderrco.fortunelink.portfoliomanagement.domain.enums.transactions;

public enum TransactionSource {
    SYSTEM,     // Generated by internal system logic
    MANUAL,     // Entered/triggered by a human (UI or back-office)
    EXTERNAL,   // Anything coming from outside (API, 3rd party, integration, webhook)
    UNKNOWN     // Fallback for unclassified or legacy cases
}