# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java Spring Backend CI with Maven

on:
  push:
    branches: [ "main", "feature/portfolio_management_v7" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'
        cache: maven

    - name: Build and Test with Maven
      working-directory: ./backend/fortunelink
      run: mvn -B clean test package -Dspring.jpa.show-sql=false -Dlogging.level.org.hibernate.SQL=ERROR --file pom.xml
      env:
        POSTGRES_VERSION: 16-alpine
        DB_USERNAME: unused
        DB_PASSWORD: unused
        DB_URL: jdbc:postgresql://localhost:5432/unused
        FMP_BASE_URL: http://localhost
        FMP_API_KEY: test_key
        REDIS_HOST: localhost
        REDIS_PORT: 6379
        REDIS_PASSWORD: unused
        SUPABASE_PROJ_URL: http://localhost:9000
        SPRING_PROFILES_ACTIVE: test
